@startuml
left to right direction
ユーザー --> (非認証状態で\n最近投稿された画像一覧を\n見ることができる)
ユーザー --> (Twitterのアカウントで\nログインして\n認証できる)
ユーザー --> (認証された状態で\nドラッグ&ドロップで画像を\n投稿できる)
ユーザー --> (認証された状態で\n画像にテロップとして\n任意の文字列を加えることができる)
ユーザー --> (テロップの文字サイズを\n変更できる)
ユーザー --> (認証された状態で\n自分が投稿した画像一覧を\n見ることができる)
ユーザー --> (ログアウトできる)
@enduml 
