# https://www.playframework.com/documentation/latest/Configuration
play.filters.headers.contentSecurityPolicy = null

# Twitter settings
mojipic.documentrooturl="http://127.0.0.1:9000"
mojipic.consumerkey="iATIcJ26jMT8l6D3Co5nTgDHY"
mojipic.consumersecret="4kBanrcs6peBEkFMxw9RCt0UeZq70EpmmAPXLAzqfhi01vLwB5"